### ISSUE TITLE
文件删除不了

### ISSUE THREAD

**Issue by cloudmisst** [d4rksystem/VMwareCloak#3]
文件删除不了

：
[*] Attempting to rename vm3dum_loader.dll...
Rename-Item : 对路径的访问被拒绝。
所在位置 C:\Users\opsx\Desktop\all\VMwareCloak-main\VMwareCloak.ps1:401 字符: 7
+             Rename-Item "$path$file" "$path$(Get-RandomString).dll"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\Windows\SysWOW64\vm3dum_loader.dll:String) [Rename-Item], Unauthor
   izedAccessException
    + FullyQualifiedErrorId : RenameItemUnauthorizedAccessError,Microsoft.PowerShell.Commands.RenameItemCommand

**Comment by d4rksystem** [comment]
Hi! Thanks for your comment. Yes, some files cannot be deleted or renamed :( This is because they may be integral for the functioning of the VM. This seems to be a specific file that is indeed required.
